export const SAUCE_TO_CONSTRUCTOR = 'SAUCE_TO_CONSTRUCTOR';
export const BUN_TO_CONSTRUCTOR = 'BUN_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const REMOVE_BUN = 'REMOVE_BUN';
export const SORTING_INGREDIENTS = 'SORTING_INGREDIENTS';